"""Added constraints

Revision ID: 09e685c8c3c8
Revises: 60b3bc2309c0
Create Date: 2024-07-17 13:41:32.734307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e685c8c3c8'
down_revision = '60b3bc2309c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('goal',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
