"""add column to goals

Revision ID: 1eb7aaace4f8
Revises: 7bbf75fb1cb6
Create Date: 2024-06-18 11:37:35.125792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb7aaace4f8'
down_revision = '7bbf75fb1cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('goals')

    # ### end Alembic commands ###
